"""Email construction and delivery for PaperScout.

Generates HTML email digests from scored papers and sends via SMTP.
"""

from __future__ import annotations

import logging
import math
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from alithia_agent.models import EmailContent, ScoredPaper
from alithia_agent.paperscout.state import SmtpConfig

logger = logging.getLogger(__name__)


EMAIL_TEMPLATE = """
<!DOCTYPE HTML>
<html>
<head>
  <style>
    .star-wrapper {{
      font-size: 1.3em;
      line-height: 1;
      display: inline-flex;
      align-items: center;
    }}
    .paper-card {{
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 16px;
      background-color: #f9f9f9;
    }}
    .paper-title {{
      font-size: 18px;
      font-weight: bold;
      color: #333;
    }}
    .paper-authors {{
      color: #666;
      margin-top: 8px;
    }}
    .paper-tldr {{
      margin-top: 12px;
      color: #444;
    }}
    .paper-links {{
      margin-top: 12px;
    }}
    .link-button {{
      display: inline-block;
      padding: 8px 16px;
      border-radius: 4px;
      font-weight: bold;
      color: #fff;
      margin-right: 8px;
    }}
    .pdf-link {{
      background-color: #d9534f;
    }}
    .code-link {{
      background-color: #5bc0de;
    }}
  </style>
</head>
<body>

<h2>PaperScout Digest {digest_date}</h2>

{content}

<br><br>
<div style="color: #999;">
  <p>This digest was generated by <strong>PaperScout</strong> for Alithia Agent.</p>
  <p>To unsubscribe, disable the paperscout subagent in your configuration.</p>
</div>

</body>
</html>
"""


def get_stars_html(score: float) -> str:
    """Generate star rating HTML."""
    if score <= 6:
        return ""
    if score >= 8:
        return "⭐" * 5

    star_count = int((score - 6) / 0.4) + 1
    return "⭐" * min(star_count, 5)


def create_paper_html(paper: ScoredPaper) -> str:
    """Create HTML block for a single paper."""
    stars = get_stars_html(paper.score)

    authors = paper.paper.authors[:5]
    authors_str = ", ".join(authors)
    if len(paper.paper.authors) > 5:
        authors_str += ", ..."

    tldr = paper.paper.tldr or paper.paper_abstract[:200] + "..."

    code_link = ""
    if hasattr(paper.paper, "code_url") and paper.paper.code_url:
        code_link = f'<a href="{paper.paper.code_url}" class="link-button code-link">Code</a>'

    return f"""
<div class="paper-card">
  <div class="paper-title">{paper.paper.title}</div>
  <div class="paper-authors">{authors_str}</div>
  <div style="margin-top: 8px;">
    <strong>Relevance:</strong> {stars} ({paper.score:.1f})
  </div>
  <div class="paper-tldr">
    <strong>TLDR:</strong> {tldr}
  </div>
  <div class="paper-links">
    <a href="{paper.paper.pdf_url}" class="link-button pdf-link">PDF</a>
    {code_link}
  </div>
</div>
"""


def create_empty_email_html() -> str:
    """Create HTML for empty digest."""
    return """
<div class="paper-card">
  <div class="paper-title">No Papers Today. Take a Rest!</div>
</div>
"""


def get_digest_date(papers: list[ScoredPaper]) -> str:
    """Get digest date from papers or current date."""
    if papers:
        dates = [p.paper.published_date for p in papers if hasattr(p.paper, "published_date") and p.paper.published_date]
        if dates:
            latest = max(dates)
            return latest.strftime("%Y/%m/%d")
    return datetime.now().strftime("%Y/%m/%d")


def construct_email_content(papers: list[ScoredPaper]) -> EmailContent:
    """Construct complete email content.

    Args:
        papers: Scored papers to include.

    Returns:
        EmailContent with subject, HTML, and paper list.
    """
    digest_date = get_digest_date(papers)

    if not papers:
        html = EMAIL_TEMPLATE.format(
            digest_date=digest_date,
            content=create_empty_email_html(),
        )
        return EmailContent(
            subject=f"PaperScout Digest {digest_date} - No Papers",
            html_body=html,
            papers=[],
        )

    paper_blocks = [create_paper_html(p) for p in papers]
    content = "".join(paper_blocks)

    html = EMAIL_TEMPLATE.format(
        digest_date=digest_date,
        content=content,
    )

    # Extract ArxivPaper from ScoredPaper
    arxiv_papers = []
    for sp in papers:
        if hasattr(sp.paper, "arxiv_id"):
            arxiv_papers.append(sp.paper)

    return EmailContent(
        subject=f"PaperScout Digest {digest_date}",
        html_body=html,
        papers=arxiv_papers,
    )


def send_email(
    email_content: EmailContent,
    smtp_config: SmtpConfig,
    recipient: str | None = None,
) -> bool:
    """Send email via SMTP.

    Args:
        email_content: Email to send.
        smtp_config: SMTP configuration.
        recipient: Override recipient (defaults to SMTP user).

    Returns:
        True if sent successfully.
    """
    recipient = recipient or smtp_config.user

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = email_content.subject
        msg["From"] = smtp_config.user
        msg["To"] = recipient

        html_part = MIMEText(email_content.html_body, "html")
        msg.attach(html_part)

        if email_content.text_body:
            text_part = MIMEText(email_content.text_body, "plain")
            msg.attach(text_part)

        logger.info(f"Connecting to SMTP: {smtp_config.host}:{smtp_config.port}")

        with smtplib.SMTP(smtp_config.host, smtp_config.port) as server:
            if smtp_config.use_tls:
                server.starttls()
            server.login(smtp_config.user, smtp_config.password)
            server.sendmail(smtp_config.user, recipient, msg.as_string())

        logger.info(f"Email sent to {recipient} ({len(email_content.papers)} papers)")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


__all__ = [
    "construct_email_content",
    "send_email",
    "get_stars_html",
    "create_paper_html",
]