"""Email construction and delivery for PaperScout.

Generates HTML email digests from scored papers and sends via SMTP.
"""

from __future__ import annotations

import logging
import math
import smtplib
from datetime import datetime
from email.header import Header
from email.mime.text import MIMEText
from email.utils import formataddr, parseaddr

from alithia_agent.models import ArxivPaper, EmailContent, ScoredPaper
from alithia_agent.paperscout.state import SmtpRuntimeConfig

# Legacy alias
SmtpConfig = SmtpRuntimeConfig

logger = logging.getLogger(__name__)


EMAIL_TEMPLATE = """
<!DOCTYPE HTML>
<html>
<head>
  <style>
    .star-wrapper {{
      font-size: 1.3em;
      line-height: 1;
      display: inline-flex;
      align-items: center;
    }}
    .half-star {{
      display: inline-block;
      width: 0.5em;
      overflow: hidden;
      white-space: nowrap;
      vertical-align: middle;
    }}
    .full-star {{
      vertical-align: middle;
    }}
  </style>
</head>
<body>

<h2>PaperScout Digest {digest_date}</h2>

<div>
    {content}
</div>

<br><br>
<div style="color: #999;">
  <p>This digest was generated by <strong>PaperScout</strong> for Alithia Agent.</p>
  <p>To unsubscribe, disable the paperscout subagent in your configuration.</p>
</div>

</body>
</html>
"""


def get_stars_html(score: float) -> str:
    """Generate star rating HTML based on score."""
    full_star = '<span class="full-star">⭐</span>'
    half_star = '<span class="half-star">⭐</span>'

    low = 6
    high = 8

    if score <= low:
        return ""
    if score >= high:
        return full_star * 5

    interval = (high - low) / 10
    star_num = math.ceil((score - low) / interval)
    full_star_num = int(star_num / 2)
    half_star_num = star_num - full_star_num * 2
    return (
        '<div class="star-wrapper">'
        + full_star * full_star_num
        + half_star * half_star_num
        + "</div>"
    )


def _format_affiliations(paper: ArxivPaper) -> str:
    """Format affiliations for display."""
    if not paper.affiliations:
        return "Unknown Affiliation"
    affiliations = paper.affiliations[:5]
    affiliations_str = ", ".join(affiliations)
    if len(paper.affiliations) > 5:
        affiliations_str += ", ..."
    return affiliations_str


def _get_tldr(paper: ScoredPaper) -> str:
    """Get TLDR text for a scored paper."""
    if isinstance(paper.paper, ArxivPaper):
        return paper.paper.tldr or paper.paper.summary[:200] + "..."
    if paper.paper.abstract:
        return paper.paper.abstract[:200] + "..."
    return "No summary available"


def create_paper_html(paper: ScoredPaper) -> str:
    """Create HTML block for a single paper."""
    stars_html = get_stars_html(paper.score)

    authors = paper.paper.authors[:5]
    authors_str = ", ".join(authors)
    if len(paper.paper.authors) > 5:
        authors_str += ", ..."

    affiliations_str = (
        _format_affiliations(paper.paper)
        if isinstance(paper.paper, ArxivPaper)
        else "Unknown Affiliation"
    )

    code_link = ""
    if isinstance(paper.paper, ArxivPaper) and paper.paper.code_url:
        code_link = (
            f'<a href="{paper.paper.code_url}" '
            'style="display: inline-block; text-decoration: none; font-size: 14px; '
            "font-weight: bold; color: #fff; background-color: #5bc0de; padding: 8px 16px; "
            'border-radius: 4px; margin-left: 8px;">Code</a>'
        )

    pdf_url = ""
    arxiv_id = ""
    if isinstance(paper.paper, ArxivPaper):
        pdf_url = paper.paper.pdf_url
        arxiv_id = paper.paper.arxiv_id
    elif paper.paper.source_url:
        pdf_url = paper.paper.source_url

    tldr = _get_tldr(paper)

    arxiv_row = ""
    if arxiv_id:
        arxiv_row = f"""
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>arXiv ID:</strong> {arxiv_id}
        </td>
    </tr>"""

    return f"""
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
        style="font-family: Arial, sans-serif; border: 1px solid #ddd;
               border-radius: 8px; padding: 16px; background-color: #f9f9f9;">
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333;">
            {paper.paper.title}
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #666; padding: 8px 0;">
            {authors_str}
            <br>
            <i>{affiliations_str}</i>
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>Relevance:</strong> {stars_html}
        </td>
    </tr>{arxiv_row}
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>TLDR:</strong> {tldr}
        </td>
    </tr>
    <tr>
        <td style="padding: 8px 0;">
            <a href="{pdf_url}"
                style="display: inline-block; text-decoration: none; font-size: 14px;
                       font-weight: bold; color: #fff; background-color: #d9534f;
                       padding: 8px 16px; border-radius: 4px;">PDF</a>
            {code_link}
        </td>
    </tr>
    </table>
    """


def create_empty_email_html() -> str:
    """Create HTML for empty digest."""
    return """
    <table border="0" cellpadding="0" cellspacing="0" width="100%"
        style="font-family: Arial, sans-serif; border: 1px solid #ddd;
               border-radius: 8px; padding: 16px; background-color: #f9f9f9;">
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333;">
            No Papers Today. Take a Rest!
        </td>
    </tr>
    </table>
    """


def get_digest_date(papers: list[ScoredPaper]) -> str:
    """Get digest date from papers or current date."""
    if papers:
        dates = [
            p.paper.published_date
            for p in papers
            if hasattr(p.paper, "published_date") and p.paper.published_date
        ]
        if dates:
            latest = max(dates)
            return latest.strftime("%Y/%m/%d")
    return datetime.now().strftime("%Y/%m/%d")


def construct_email_content(papers: list[ScoredPaper]) -> EmailContent:
    """Construct complete email content.

    Args:
        papers: Scored papers to include.

    Returns:
        EmailContent with subject, HTML, and paper list.
    """
    digest_date = get_digest_date(papers)

    if not papers:
        html = EMAIL_TEMPLATE.format(
            digest_date=digest_date,
            content=create_empty_email_html(),
        )
        return EmailContent(
            subject=f"PaperScout Digest {digest_date} - No Papers",
            html_body=html,
            papers=[],
        )

    paper_blocks = [create_paper_html(p) for p in papers]
    content = "<br>".join(paper_blocks)

    html = EMAIL_TEMPLATE.format(
        digest_date=digest_date,
        content=content,
    )

    arxiv_papers = []
    for sp in papers:
        if hasattr(sp.paper, "arxiv_id"):
            arxiv_papers.append(sp.paper)

    return EmailContent(
        subject=f"PaperScout Digest {digest_date}",
        html_body=html,
        papers=arxiv_papers,
    )


def _format_addr(address: str) -> str:
    """Format email address with UTF-8 encoded display name."""
    name, addr = parseaddr(address)
    return formataddr((Header(name, "utf-8").encode(), addr))


def send_email(
    email_content: EmailContent,
    smtp_config: SmtpConfig,
    recipient: str | None = None,
) -> bool:
    """Send email via SMTP.

    Args:
        email_content: Email to send.
        smtp_config: SMTP configuration.
        recipient: Override recipient (defaults to SMTP user).

    Returns:
        True if sent successfully.
    """
    recipient = recipient or smtp_config.user

    try:
        msg = MIMEText(email_content.html_body, "html", "utf-8")
        msg["From"] = _format_addr(f"PaperScout <{smtp_config.user}>")
        msg["To"] = _format_addr(f"You <{recipient}>")
        msg["Subject"] = Header(email_content.subject, "utf-8").encode()

        logger.info(f"Connecting to SMTP: {smtp_config.host}:{smtp_config.port}")

        if smtp_config.port == 465:
            with smtplib.SMTP_SSL(smtp_config.host, smtp_config.port) as server:
                server.login(smtp_config.user, smtp_config.password)
                server.sendmail(smtp_config.user, recipient, msg.as_string())
        else:
            with smtplib.SMTP(smtp_config.host, smtp_config.port) as server:
                if smtp_config.use_tls:
                    server.starttls()
                server.login(smtp_config.user, smtp_config.password)
                server.sendmail(smtp_config.user, recipient, msg.as_string())

        logger.info(f"Email sent to {recipient} ({len(email_content.papers)} papers)")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


__all__ = [
    "construct_email_content",
    "send_email",
    "get_stars_html",
    "create_paper_html",
]
