"""ResearchInterest data model — one knowledge unit from a Markdown file.

See RFC-010 §6.1. The body is set by the loader after stripping the YAML
frontmatter; `get_searchable_text()` is what the PaperScout reranker embeds.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ResearchInterest(BaseModel):
    """One knowledge unit parsed from a research_interests/*.md file.

    A unit is either hand-written (``source="manual"``) or generated by the
    Zotero sync step (``source="zotero"``). Both origins are treated
    uniformly by the matcher: each unit contributes one embedding row.
    """

    model_config = ConfigDict(extra="allow")

    title: str
    source: Literal["manual", "zotero"] = "manual"
    weight: float = Field(default=1.0, ge=0.0)
    arxiv_categories: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    notes: str = ""
    date_added: date | None = None
    zotero_item_key: str | None = None

    # Raw markdown body (frontmatter stripped), populated by the loader.
    body: str = ""

    @property
    def display_title(self) -> str:
        """Human-readable unit label."""
        return self.title

    def get_searchable_text(self) -> str:
        """Text fed to the embedder: notes + body + tags (RFC-010 §5.4).

        Mirrors the weighting philosophy of ``ZoteroPaper.get_searchable_text``
        in RFC-008 §5.3 — title and tags contribute, but for interest units
        the body prose is the primary signal.
        """
        parts: list[str] = []
        if self.notes:
            parts.append(self.notes)
        if self.body:
            parts.append(self.body)
        if self.tags:
            parts.append(" ".join(self.tags))
        return " ".join(parts)


__all__ = ["ResearchInterest"]
